[package]
name = "unspoken"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.17", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
openai_api_rust = "0.1.9"
thiserror = "1.0.63"
