[package]
name = "unspoken"
description = "Chatbot API client library and CLI interface."
license = "MIT"
repository = "https://github.com/dmitry-markin/unspoken"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.17", features = ["derive", "wrap_help"] }
colored = "2.1.0"
dirs = "5.0.1"
openai_api_rust = "0.1.9"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.63"
toml = "0.8.19"
