[package]
name = "jutella"
description = "Chatbot API client library and CLI interface."
license = "MIT"
repository = "https://github.com/dmitry-markin/jutella"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.89", optional = true }
clap = { version = "4.5.17", features = ["derive", "wrap_help"], optional = true }
colored = { version = "2.1.0", optional = true }
dirs = { version = "5.0.1", optional = true }
openai_api_rust = "0.1.9"
reqwest = { version = "0.12.7", default-features = false, features = ["rustls-tls", "http2", "zstd", "hickory-dns"] }
serde = { version = "1.0.210", features = ["derive"], optional = true }
serde_json = "1.0.128"
thiserror = "1.0.63"
toml = { version = "0.8.19", optional = true }

[features]
default = ["bin"]
bin = ["dep:anyhow", "dep:clap", "dep:colored", "dep:dirs", "dep:serde", "dep:toml"]
