// Copyright (c) 2024 `jutella` chatbot API client developers
//
// SPDX-License-Identifier: MIT
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

//! OpenAI REST API client.

use crate::chat_client::openai_api::chat_completions::{ChatCompletions, ChatCompletionsBody};
use reqwest::{
    header::{HeaderValue, InvalidHeaderValue, AUTHORIZATION},
    Client, ClientBuilder,
};
use std::time::Duration;

const CHAT_COMPLETIONS_ENDPOINT: &str = "v1/chat/completions";
const REQUEST_TIMEOUT: Duration = Duration::from_secs(20);

/// OpenAI REST API client.
pub struct OpenAiClient {
    client: Client,
    api_key: String,
    base_url: String,
}

impl OpenAiClient {
    pub fn new(api_key: String, base_url: String) -> Result<Self, Error> {
        let client = ClientBuilder::new()
            .default_headers(
                [(
                    AUTHORIZATION,
                    HeaderValue::from_str(&format!("Bearer {api_key}"))?,
                )]
                .into_iter()
                .collect(),
            )
            .timeout(REQUEST_TIMEOUT)
            .build()?;

        Ok(Self {
            client,
            api_key,
            base_url,
        })
    }

    pub async fn chat_completions(
        &mut self,
        body: ChatCompletionsBody,
    ) -> Result<ChatCompletions, Error> {
        Ok(self.client
            .post(self.base_url.clone() + CHAT_COMPLETIONS_ENDPOINT)
            .json(&body)
            .send()
            .await?
            .json()
            .await?)
    }
}

// Errors generated by [`OpenAiClient`].
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// Invalid API key charcters.
    #[error("Non ASCII / non visible characters in API key")]
    InvalidCharacersInApiKey(#[from] InvalidHeaderValue),

    /// Reqwest error.
    #[error("Request error: {0}")]
    RequestError(#[from] reqwest::Error),
}
